### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by memmaina** [mcvendrell/SlimFramework4LoginAuth#2]
I think I have followed the instructions to the letter, but I got '405 Method Not Allowed'. I am new to slim, so maybe it's the setup that is wrong - can you help

Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/8.1.2

405 Method Not Allowed

The application could not run because of the following error:
Details
Type: Slim\Exception\HttpMethodNotAllowedException
Code: 405
Message: Method not allowed. Must be one of: OPTIONS
File: C:\xampp\htdocs\SlimFramework4LoginAuth\vendor\slim\slim\Slim\Middleware\RoutingMiddleware.php
Line: 79

Thank you in advance

**Comment by mcvendrell** [comment]
Hi.

From the type of message, I assume it may be a CORS issue, so maybe you are not sending the correct headers or have some wrong configuration.

Anyway, check this and maybe you can find the problem https://www.slimframework.com/docs/v4/cookbook/enable-cors.html
