### ISSUE TITLE
_SESSION is not working for CORS

### ISSUE THREAD

**Issue by alejomj** [mcvendrell/SlimFramework4LoginAuth#3]
$_SESSION does not work with CORS fetch

**Comment by mcvendrell** [comment]
If you have a problem with CORS it means you are mixing your application with another different source.

In that case, you will need to allow CORS in your server side. You will find a lot of CORS examples and explanations on the web.
Also https://www.slimframework.com/docs/v4/cookbook/enable-cors.html
